// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

public interface ComponentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.integrator.grpc.Component)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsInput = 2;</code>
   */
  int getParamsInputCount();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsInput = 2;</code>
   */
  boolean containsParamsInput(
          String key);
  /**
   * Use {@link #getParamsInputMap()} instead.
   */
  @Deprecated
  java.util.Map<String, DataType>
  getParamsInput();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsInput = 2;</code>
   */
  java.util.Map<String, DataType>
  getParamsInputMap();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsInput = 2;</code>
   */

  DataType getParamsInputOrDefault(
          String key,
          DataType defaultValue);
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsInput = 2;</code>
   */

  DataType getParamsInputOrThrow(
          String key);

  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsOutput = 3;</code>
   */
  int getParamsOutputCount();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsOutput = 3;</code>
   */
  boolean containsParamsOutput(
          String key);
  /**
   * Use {@link #getParamsOutputMap()} instead.
   */
  @Deprecated
  java.util.Map<String, DataType>
  getParamsOutput();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsOutput = 3;</code>
   */
  java.util.Map<String, DataType>
  getParamsOutputMap();
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsOutput = 3;</code>
   */

  DataType getParamsOutputOrDefault(
          String key,
          DataType defaultValue);
  /**
   * <code>map&lt;string, .com.integrator.grpc.DataType&gt; paramsOutput = 3;</code>
   */

  DataType getParamsOutputOrThrow(
          String key);
}
