// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

/**
 * Protobuf type {@code com.integrator.grpc.DataType}
 */
public  final class DataType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.integrator.grpc.DataType)
    DataTypeOrBuilder {
  // Use DataType.newBuilder() to construct.
  private DataType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataType() {
    str_ = "";
    int_ = 0;
    boolean_ = false;
    byteall_ = com.google.protobuf.ByteString.EMPTY;
    type_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DataType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            str_ = s;
            break;
          }
          case 16: {

            int_ = input.readInt32();
            break;
          }
          case 24: {

            boolean_ = input.readBool();
            break;
          }
          case 34: {

            byteall_ = input.readBytes();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_DataType_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_DataType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DataType.class, Builder.class);
  }

  /**
   * Protobuf enum {@code com.integrator.grpc.DataType.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INT = 0;</code>
     */
    INT(0),
    /**
     * <code>STR = 1;</code>
     */
    STR(1),
    /**
     * <code>BOOL = 2;</code>
     */
    BOOL(2),
    /**
     * <code>BYTES = 3;</code>
     */
    BYTES(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INT = 0;</code>
     */
    public static final int INT_VALUE = 0;
    /**
     * <code>STR = 1;</code>
     */
    public static final int STR_VALUE = 1;
    /**
     * <code>BOOL = 2;</code>
     */
    public static final int BOOL_VALUE = 2;
    /**
     * <code>BYTES = 3;</code>
     */
    public static final int BYTES_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return INT;
        case 1: return STR;
        case 2: return BOOL;
        case 3: return BYTES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DataType.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.integrator.grpc.DataType.Type)
  }

  public static final int STR_FIELD_NUMBER = 1;
  private volatile Object str_;
  /**
   * <code>optional string str = 1;</code>
   */
  public String getStr() {
    Object ref = str_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>optional string str = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStrBytes() {
    Object ref = str_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INT_FIELD_NUMBER = 2;
  private int int_;
  /**
   * <code>optional int32 int = 2;</code>
   */
  public int getInt() {
    return int_;
  }

  public static final int BOOLEAN_FIELD_NUMBER = 3;
  private boolean boolean_;
  /**
   * <code>optional bool boolean = 3;</code>
   */
  public boolean getBoolean() {
    return boolean_;
  }

  public static final int BYTEALL_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString byteall_;
  /**
   * <code>optional bytes byteall = 4;</code>
   */
  public com.google.protobuf.ByteString getByteall() {
    return byteall_;
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private int type_;
  /**
   * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
   */
  public Type getType() {
    Type result = Type.valueOf(type_);
    return result == null ? Type.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, str_);
    }
    if (int_ != 0) {
      output.writeInt32(2, int_);
    }
    if (boolean_ != false) {
      output.writeBool(3, boolean_);
    }
    if (!byteall_.isEmpty()) {
      output.writeBytes(4, byteall_);
    }
    if (type_ != Type.INT.getNumber()) {
      output.writeEnum(5, type_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, str_);
    }
    if (int_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, int_);
    }
    if (boolean_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, boolean_);
    }
    if (!byteall_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, byteall_);
    }
    if (type_ != Type.INT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, type_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DataType)) {
      return super.equals(obj);
    }
    DataType other = (DataType) obj;

    boolean result = true;
    result = result && getStr()
        .equals(other.getStr());
    result = result && (getInt()
        == other.getInt());
    result = result && (getBoolean()
        == other.getBoolean());
    result = result && getByteall()
        .equals(other.getByteall());
    result = result && type_ == other.type_;
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (37 * hash) + INT_FIELD_NUMBER;
    hash = (53 * hash) + getInt();
    hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolean());
    hash = (37 * hash) + BYTEALL_FIELD_NUMBER;
    hash = (53 * hash) + getByteall().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DataType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DataType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DataType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DataType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DataType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DataType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DataType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DataType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DataType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DataType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DataType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.integrator.grpc.DataType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.integrator.grpc.DataType)
      DataTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_DataType_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_DataType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataType.class, Builder.class);
    }

    // Construct using com.integrator.grpc.DataType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      str_ = "";

      int_ = 0;

      boolean_ = false;

      byteall_ = com.google.protobuf.ByteString.EMPTY;

      type_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_DataType_descriptor;
    }

    public DataType getDefaultInstanceForType() {
      return DataType.getDefaultInstance();
    }

    public DataType build() {
      DataType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public DataType buildPartial() {
      DataType result = new DataType(this);
      result.str_ = str_;
      result.int_ = int_;
      result.boolean_ = boolean_;
      result.byteall_ = byteall_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DataType) {
        return mergeFrom((DataType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DataType other) {
      if (other == DataType.getDefaultInstance()) return this;
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        onChanged();
      }
      if (other.getInt() != 0) {
        setInt(other.getInt());
      }
      if (other.getBoolean() != false) {
        setBoolean(other.getBoolean());
      }
      if (other.getByteall() != com.google.protobuf.ByteString.EMPTY) {
        setByteall(other.getByteall());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DataType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DataType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object str_ = "";
    /**
     * <code>optional string str = 1;</code>
     */
    public String getStr() {
      Object ref = str_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string str = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string str = 1;</code>
     */
    public Builder setStr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      str_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string str = 1;</code>
     */
    public Builder clearStr() {
      
      str_ = getDefaultInstance().getStr();
      onChanged();
      return this;
    }
    /**
     * <code>optional string str = 1;</code>
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      str_ = value;
      onChanged();
      return this;
    }

    private int int_ ;
    /**
     * <code>optional int32 int = 2;</code>
     */
    public int getInt() {
      return int_;
    }
    /**
     * <code>optional int32 int = 2;</code>
     */
    public Builder setInt(int value) {
      
      int_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 int = 2;</code>
     */
    public Builder clearInt() {
      
      int_ = 0;
      onChanged();
      return this;
    }

    private boolean boolean_ ;
    /**
     * <code>optional bool boolean = 3;</code>
     */
    public boolean getBoolean() {
      return boolean_;
    }
    /**
     * <code>optional bool boolean = 3;</code>
     */
    public Builder setBoolean(boolean value) {
      
      boolean_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool boolean = 3;</code>
     */
    public Builder clearBoolean() {
      
      boolean_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString byteall_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes byteall = 4;</code>
     */
    public com.google.protobuf.ByteString getByteall() {
      return byteall_;
    }
    /**
     * <code>optional bytes byteall = 4;</code>
     */
    public Builder setByteall(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      byteall_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes byteall = 4;</code>
     */
    public Builder clearByteall() {
      
      byteall_ = getDefaultInstance().getByteall();
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
     */
    public Type getType() {
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
     */
    public Builder setType(Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.integrator.grpc.DataType)
  }

  // @@protoc_insertion_point(class_scope:com.integrator.grpc.DataType)
  private static final DataType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DataType();
  }

  public static DataType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataType>
      PARSER = new com.google.protobuf.AbstractParser<DataType>() {
    public DataType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataType> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DataType> getParserForType() {
    return PARSER;
  }

  public DataType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

