// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

public interface DataTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.integrator.grpc.DataType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string str = 1;</code>
   */
  String getStr();
  /**
   * <code>optional string str = 1;</code>
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <code>optional int32 int = 2;</code>
   */
  int getInt();

  /**
   * <code>optional bool boolean = 3;</code>
   */
  boolean getBoolean();

  /**
   * <code>optional bytes byteall = 4;</code>
   */
  com.google.protobuf.ByteString getByteall();

  /**
   * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .com.integrator.grpc.DataType.Type type = 5;</code>
   */
  DataType.Type getType();
}
