// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

/**
 * Protobuf type {@code com.integrator.grpc.ExecuteRequest}
 */
public  final class ExecuteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.integrator.grpc.ExecuteRequest)
    ExecuteRequestOrBuilder {
  // Use ExecuteRequest.newBuilder() to construct.
  private ExecuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ExecuteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Component.Builder subBuilder = null;
            if (component_ != null) {
              subBuilder = component_.toBuilder();
            }
            component_ = input.readMessage(Component.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(component_);
              component_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_ExecuteRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_ExecuteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExecuteRequest.class, Builder.class);
  }

  public static final int COMPONENT_FIELD_NUMBER = 1;
  private Component component_;
  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  public boolean hasComponent() {
    return component_ != null;
  }
  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  public Component getComponent() {
    return component_ == null ? Component.getDefaultInstance() : component_;
  }
  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  public ComponentOrBuilder getComponentOrBuilder() {
    return getComponent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (component_ != null) {
      output.writeMessage(1, getComponent());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (component_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getComponent());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExecuteRequest)) {
      return super.equals(obj);
    }
    ExecuteRequest other = (ExecuteRequest) obj;

    boolean result = true;
    result = result && (hasComponent() == other.hasComponent());
    if (hasComponent()) {
      result = result && getComponent()
          .equals(other.getComponent());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasComponent()) {
      hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getComponent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExecuteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.integrator.grpc.ExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.integrator.grpc.ExecuteRequest)
      ExecuteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_ExecuteRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_ExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExecuteRequest.class, Builder.class);
    }

    // Construct using com.integrator.grpc.ExecuteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (componentBuilder_ == null) {
        component_ = null;
      } else {
        component_ = null;
        componentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_ExecuteRequest_descriptor;
    }

    public ExecuteRequest getDefaultInstanceForType() {
      return ExecuteRequest.getDefaultInstance();
    }

    public ExecuteRequest build() {
      ExecuteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ExecuteRequest buildPartial() {
      ExecuteRequest result = new ExecuteRequest(this);
      if (componentBuilder_ == null) {
        result.component_ = component_;
      } else {
        result.component_ = componentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExecuteRequest) {
        return mergeFrom((ExecuteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExecuteRequest other) {
      if (other == ExecuteRequest.getDefaultInstance()) return this;
      if (other.hasComponent()) {
        mergeComponent(other.getComponent());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExecuteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExecuteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Component component_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Component, Component.Builder, ComponentOrBuilder> componentBuilder_;
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public boolean hasComponent() {
      return componentBuilder_ != null || component_ != null;
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Component getComponent() {
      if (componentBuilder_ == null) {
        return component_ == null ? Component.getDefaultInstance() : component_;
      } else {
        return componentBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Builder setComponent(Component value) {
      if (componentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        component_ = value;
        onChanged();
      } else {
        componentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Builder setComponent(
        Component.Builder builderForValue) {
      if (componentBuilder_ == null) {
        component_ = builderForValue.build();
        onChanged();
      } else {
        componentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Builder mergeComponent(Component value) {
      if (componentBuilder_ == null) {
        if (component_ != null) {
          component_ =
            Component.newBuilder(component_).mergeFrom(value).buildPartial();
        } else {
          component_ = value;
        }
        onChanged();
      } else {
        componentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Builder clearComponent() {
      if (componentBuilder_ == null) {
        component_ = null;
        onChanged();
      } else {
        component_ = null;
        componentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public Component.Builder getComponentBuilder() {
      
      onChanged();
      return getComponentFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    public ComponentOrBuilder getComponentOrBuilder() {
      if (componentBuilder_ != null) {
        return componentBuilder_.getMessageOrBuilder();
      } else {
        return component_ == null ?
            Component.getDefaultInstance() : component_;
      }
    }
    /**
     * <code>optional .com.integrator.grpc.Component component = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Component, Component.Builder, ComponentOrBuilder>
        getComponentFieldBuilder() {
      if (componentBuilder_ == null) {
        componentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Component, Component.Builder, ComponentOrBuilder>(
                getComponent(),
                getParentForChildren(),
                isClean());
        component_ = null;
      }
      return componentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.integrator.grpc.ExecuteRequest)
  }

  // @@protoc_insertion_point(class_scope:com.integrator.grpc.ExecuteRequest)
  private static final ExecuteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExecuteRequest();
  }

  public static ExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteRequest>() {
    public ExecuteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecuteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecuteRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExecuteRequest> getParserForType() {
    return PARSER;
  }

  public ExecuteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

