// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.integrator.grpc.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  boolean hasComponent();
  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  Component getComponent();
  /**
   * <code>optional .com.integrator.grpc.Component component = 1;</code>
   */
  ComponentOrBuilder getComponentOrBuilder();
}
