// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

public interface SaveChainResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.integrator.grpc.SaveChainResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();
}
