// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrator.proto

package com.integrator.grpc;

/**
 * Protobuf type {@code com.integrator.grpc.StartRequest}
 */
public  final class StartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.integrator.grpc.StartRequest)
    StartRequestOrBuilder {
  // Use StartRequest.newBuilder() to construct.
  private StartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartRequest() {
    chainId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private StartRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            chainId_ = s;
            break;
          }
          case 18: {
            Component.Builder subBuilder = null;
            if (startComponent_ != null) {
              subBuilder = startComponent_.toBuilder();
            }
            startComponent_ = input.readMessage(Component.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startComponent_);
              startComponent_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_StartRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return IntegratorOuterClass.internal_static_com_integrator_grpc_StartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StartRequest.class, Builder.class);
  }

  public static final int CHAINID_FIELD_NUMBER = 1;
  private volatile Object chainId_;
  /**
   * <code>optional string chainId = 1;</code>
   */
  public String getChainId() {
    Object ref = chainId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      chainId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string chainId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getChainIdBytes() {
    Object ref = chainId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      chainId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTCOMPONENT_FIELD_NUMBER = 2;
  private Component startComponent_;
  /**
   * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
   */
  public boolean hasStartComponent() {
    return startComponent_ != null;
  }
  /**
   * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
   */
  public Component getStartComponent() {
    return startComponent_ == null ? Component.getDefaultInstance() : startComponent_;
  }
  /**
   * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
   */
  public ComponentOrBuilder getStartComponentOrBuilder() {
    return getStartComponent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChainIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chainId_);
    }
    if (startComponent_ != null) {
      output.writeMessage(2, getStartComponent());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChainIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chainId_);
    }
    if (startComponent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStartComponent());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StartRequest)) {
      return super.equals(obj);
    }
    StartRequest other = (StartRequest) obj;

    boolean result = true;
    result = result && getChainId()
        .equals(other.getChainId());
    result = result && (hasStartComponent() == other.hasStartComponent());
    if (hasStartComponent()) {
      result = result && getStartComponent()
          .equals(other.getStartComponent());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CHAINID_FIELD_NUMBER;
    hash = (53 * hash) + getChainId().hashCode();
    if (hasStartComponent()) {
      hash = (37 * hash) + STARTCOMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getStartComponent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.integrator.grpc.StartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.integrator.grpc.StartRequest)
      StartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_StartRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_StartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StartRequest.class, Builder.class);
    }

    // Construct using com.integrator.grpc.StartRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      chainId_ = "";

      if (startComponentBuilder_ == null) {
        startComponent_ = null;
      } else {
        startComponent_ = null;
        startComponentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return IntegratorOuterClass.internal_static_com_integrator_grpc_StartRequest_descriptor;
    }

    public StartRequest getDefaultInstanceForType() {
      return StartRequest.getDefaultInstance();
    }

    public StartRequest build() {
      StartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public StartRequest buildPartial() {
      StartRequest result = new StartRequest(this);
      result.chainId_ = chainId_;
      if (startComponentBuilder_ == null) {
        result.startComponent_ = startComponent_;
      } else {
        result.startComponent_ = startComponentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StartRequest) {
        return mergeFrom((StartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StartRequest other) {
      if (other == StartRequest.getDefaultInstance()) return this;
      if (!other.getChainId().isEmpty()) {
        chainId_ = other.chainId_;
        onChanged();
      }
      if (other.hasStartComponent()) {
        mergeStartComponent(other.getStartComponent());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StartRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StartRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object chainId_ = "";
    /**
     * <code>optional string chainId = 1;</code>
     */
    public String getChainId() {
      Object ref = chainId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        chainId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string chainId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      Object ref = chainId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        chainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string chainId = 1;</code>
     */
    public Builder setChainId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chainId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string chainId = 1;</code>
     */
    public Builder clearChainId() {
      
      chainId_ = getDefaultInstance().getChainId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string chainId = 1;</code>
     */
    public Builder setChainIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chainId_ = value;
      onChanged();
      return this;
    }

    private Component startComponent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Component, Component.Builder, ComponentOrBuilder> startComponentBuilder_;
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public boolean hasStartComponent() {
      return startComponentBuilder_ != null || startComponent_ != null;
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Component getStartComponent() {
      if (startComponentBuilder_ == null) {
        return startComponent_ == null ? Component.getDefaultInstance() : startComponent_;
      } else {
        return startComponentBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Builder setStartComponent(Component value) {
      if (startComponentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startComponent_ = value;
        onChanged();
      } else {
        startComponentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Builder setStartComponent(
        Component.Builder builderForValue) {
      if (startComponentBuilder_ == null) {
        startComponent_ = builderForValue.build();
        onChanged();
      } else {
        startComponentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Builder mergeStartComponent(Component value) {
      if (startComponentBuilder_ == null) {
        if (startComponent_ != null) {
          startComponent_ =
            Component.newBuilder(startComponent_).mergeFrom(value).buildPartial();
        } else {
          startComponent_ = value;
        }
        onChanged();
      } else {
        startComponentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Builder clearStartComponent() {
      if (startComponentBuilder_ == null) {
        startComponent_ = null;
        onChanged();
      } else {
        startComponent_ = null;
        startComponentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public Component.Builder getStartComponentBuilder() {
      
      onChanged();
      return getStartComponentFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    public ComponentOrBuilder getStartComponentOrBuilder() {
      if (startComponentBuilder_ != null) {
        return startComponentBuilder_.getMessageOrBuilder();
      } else {
        return startComponent_ == null ?
            Component.getDefaultInstance() : startComponent_;
      }
    }
    /**
     * <code>optional .com.integrator.grpc.Component startComponent = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Component, Component.Builder, ComponentOrBuilder>
        getStartComponentFieldBuilder() {
      if (startComponentBuilder_ == null) {
        startComponentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Component, Component.Builder, ComponentOrBuilder>(
                getStartComponent(),
                getParentForChildren(),
                isClean());
        startComponent_ = null;
      }
      return startComponentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.integrator.grpc.StartRequest)
  }

  // @@protoc_insertion_point(class_scope:com.integrator.grpc.StartRequest)
  private static final StartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StartRequest();
  }

  public static StartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartRequest>
      PARSER = new com.google.protobuf.AbstractParser<StartRequest>() {
    public StartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StartRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StartRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StartRequest> getParserForType() {
    return PARSER;
  }

  public StartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

